name: C/I testing with coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - name: Debugging
      run: |
        cat /etc/apt/sources.list
        find /etc/apt/sources.list.d/ -type f -exec echo ----------------{} \; -exec cat {} \;
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc texlive-xetex
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        pip3 install coveralls
    - name: curlylint
      run: |
        tools/curlylint.sh
    - name: Test with pytest
      run: |
        source tools/environment-variables-for-test.sh
        cd SchemaCollaboration
        coverage erase
        coverage run manage.py test
    - name: Upload coverage to Coveralls
      run: |
        cd SchemaCollaboration
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
